---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.vgalaxy
  resources:
  - rollingmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.vgalaxy
  resources:
  - rollingmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - demo.vgalaxy
  resources:
  - rollingmonitors/status
  verbs:
  - get
  - patch
  - update
